# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Selector(object):
    def setupUi(self, Selector):
        Selector.setObjectName("Selector")
        Selector.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=Selector)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 40, 701, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditInput = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEditInput.setObjectName("lineEditInput")
        self.gridLayout.addWidget(self.lineEditInput, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditOutput = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEditOutput.setObjectName("lineEditOutput")
        self.gridLayout.addWidget(self.lineEditOutput, 1, 1, 1, 1)
        self.pushButtonInput = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButtonInput.setObjectName("pushButtonInput")
        self.gridLayout.addWidget(self.pushButtonInput, 0, 2, 1, 1)
        self.pushButtonOutput = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButtonOutput.setObjectName("pushButtonOutput")
        self.gridLayout.addWidget(self.pushButtonOutput, 1, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(600, 480, 152, 32))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        Selector.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Selector)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        Selector.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Selector)
        self.statusbar.setObjectName("statusbar")
        Selector.setStatusBar(self.statusbar)

        self.retranslateUi(Selector)
        QtCore.QMetaObject.connectSlotsByName(Selector)

    def retranslateUi(self, Selector):
        _translate = QtCore.QCoreApplication.translate
        Selector.setWindowTitle(_translate("Selector", "MainWindow"))
        self.label.setText(_translate("Selector", "File to convert: "))
        self.label_2.setText(_translate("Selector", "Output folder:"))
        self.pushButtonInput.setText(_translate("Selector", "Browse files"))
        self.pushButtonOutput.setText(_translate("Selector", "Browse folders"))
