# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selector.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Selector(object):
    def setupUi(self, Selector):
        Selector.setObjectName("Selector")
        Selector.resize(615, 372)
        self.buttonBox = QtWidgets.QDialogButtonBox(Selector)
        self.buttonBox.setGeometry(QtCore.QRect(250, 320, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(Selector)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 571, 291))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditInput = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditInput.setObjectName("lineEditInput")
        self.gridLayout.addWidget(self.lineEditInput, 0, 1, 1, 1)
        self.lineEditOutput = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditOutput.setClearButtonEnabled(False)
        self.lineEditOutput.setObjectName("lineEditOutput")
        self.gridLayout.addWidget(self.lineEditOutput, 2, 1, 1, 1)
        self.pushButtonInput = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonInput.setObjectName("pushButtonInput")
        self.gridLayout.addWidget(self.pushButtonInput, 0, 2, 1, 1)
        self.pushButtonOutput = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonOutput.setObjectName("pushButtonOutput")
        self.gridLayout.addWidget(self.pushButtonOutput, 2, 2, 1, 1)

        self.retranslateUi(Selector)
        self.buttonBox.accepted.connect(Selector.accept) # type: ignore
        self.buttonBox.rejected.connect(Selector.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Selector)

    def retranslateUi(self, Selector):
        _translate = QtCore.QCoreApplication.translate
        Selector.setWindowTitle(_translate("Selector", "mzXMLConverter"))
        self.label_2.setText(_translate("Selector", "Output folder:"))
        self.label.setText(_translate("Selector", "File to convert: "))
        self.pushButtonInput.setText(_translate("Selector", "Browse files"))
        self.pushButtonOutput.setText(_translate("Selector", "Browse folders"))
